$pdf_mode = 4;
$postscript_mode = $dvi_mode = 0;
$aux_dir = "./build";
$clean_ext .= " acr acn alg glo glo-abr gls gls-abr glg glg-abr %R.bbl ist run.xml";

# glossaries
add_cus_dep( 'acn', 'acr', 0, 'makeglossaries' );
add_cus_dep( 'glo', 'gls', 0, 'makeglossaries' );

sub makeglossaries {
  my ($base_name, $path) = fileparse( $_[0] );
  my @args = ( "-q", "-d", $path, $base_name );
  if ($silent) { unshift @args, "-q"; }
  return system "makeglossaries", "-d", $path, $base_name;
}

